# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae0b7ac674b3898397f36bf7deaa1db057861d0cfad1e2bcdf129f9f2e13f80a39a824c6cd4dd595cbeb350522566fe01866046efc9eadf9203ebf678c2d8d6c

test:
  secret_key_base: 16fae261074c67db2e3809c02437b3d3f5bfffb2b9e026769411c8ed39f0d92dcc7a8958ca7c0583a53fac887083576717e7a88d41308e09e6f743e715310e0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
